// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/gin-gonic/gin"
	"github.com/ryvasa/go-super-farmer/config"
	"github.com/ryvasa/go-super-farmer/internal/delivery/http/handler/user"
	"github.com/ryvasa/go-super-farmer/internal/delivery/http/route"
	"github.com/ryvasa/go-super-farmer/internal/repository/user"
	"github.com/ryvasa/go-super-farmer/internal/usecase"
)

// Injectors from wire.go:

func InitializeRouter() (*gin.Engine, error) {
	db, err := config.ConnectDB()
	if err != nil {
		return nil, err
	}
	userRepository := repository.NewUserRepository(db)
	userUsecase := usecase.NewUserUsecase(userRepository)
	userHandler := handler.NewUserHandler(userUsecase)
	engine := route.NewRouter(userHandler)
	return engine, nil
}
