// Code generated by MockGen. DO NOT EDIT.
// Source: utils/token.go

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	jwt "github.com/golang-jwt/jwt/v5"
	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockTokenUtil is a mock of TokenUtil interface.
type MockTokenUtil struct {
	ctrl     *gomock.Controller
	recorder *MockTokenUtilMockRecorder
}

// MockTokenUtilMockRecorder is the mock recorder for MockTokenUtil.
type MockTokenUtilMockRecorder struct {
	mock *MockTokenUtil
}

// NewMockTokenUtil creates a new mock instance.
func NewMockTokenUtil(ctrl *gomock.Controller) *MockTokenUtil {
	mock := &MockTokenUtil{ctrl: ctrl}
	mock.recorder = &MockTokenUtilMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenUtil) EXPECT() *MockTokenUtilMockRecorder {
	return m.recorder
}

// ExtractClaims mocks base method.
func (m *MockTokenUtil) ExtractClaims(tokenString string) (jwt.MapClaims, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExtractClaims", tokenString)
	ret0, _ := ret[0].(jwt.MapClaims)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExtractClaims indicates an expected call of ExtractClaims.
func (mr *MockTokenUtilMockRecorder) ExtractClaims(tokenString interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExtractClaims", reflect.TypeOf((*MockTokenUtil)(nil).ExtractClaims), tokenString)
}

// GenerateToken mocks base method.
func (m *MockTokenUtil) GenerateToken(id uuid.UUID, role string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateToken", id, role)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateToken indicates an expected call of GenerateToken.
func (mr *MockTokenUtilMockRecorder) GenerateToken(id, role interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateToken", reflect.TypeOf((*MockTokenUtil)(nil).GenerateToken), id, role)
}

// ValidateToken mocks base method.
func (m *MockTokenUtil) ValidateToken(tokenString string) (*jwt.Token, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateToken", tokenString)
	ret0, _ := ret[0].(*jwt.Token)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateToken indicates an expected call of ValidateToken.
func (mr *MockTokenUtilMockRecorder) ValidateToken(tokenString interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateToken", reflect.TypeOf((*MockTokenUtil)(nil).ValidateToken), tokenString)
}
