// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/demand_history_repository.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
	domain "github.com/ryvasa/go-super-farmer/internal/model/domain"
)

// MockDemandHistoryRepository is a mock of DemandHistoryRepository interface.
type MockDemandHistoryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockDemandHistoryRepositoryMockRecorder
}

// MockDemandHistoryRepositoryMockRecorder is the mock recorder for MockDemandHistoryRepository.
type MockDemandHistoryRepositoryMockRecorder struct {
	mock *MockDemandHistoryRepository
}

// NewMockDemandHistoryRepository creates a new mock instance.
func NewMockDemandHistoryRepository(ctrl *gomock.Controller) *MockDemandHistoryRepository {
	mock := &MockDemandHistoryRepository{ctrl: ctrl}
	mock.recorder = &MockDemandHistoryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDemandHistoryRepository) EXPECT() *MockDemandHistoryRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockDemandHistoryRepository) Create(ctx context.Context, supply *domain.DemandHistory) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, supply)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockDemandHistoryRepositoryMockRecorder) Create(ctx, supply interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockDemandHistoryRepository)(nil).Create), ctx, supply)
}

// FindAll mocks base method.
func (m *MockDemandHistoryRepository) FindAll(ctx context.Context) (*[]domain.DemandHistory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", ctx)
	ret0, _ := ret[0].(*[]domain.DemandHistory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockDemandHistoryRepositoryMockRecorder) FindAll(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockDemandHistoryRepository)(nil).FindAll), ctx)
}

// FindByCommodityID mocks base method.
func (m *MockDemandHistoryRepository) FindByCommodityID(ctx context.Context, id uuid.UUID) (*[]domain.DemandHistory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByCommodityID", ctx, id)
	ret0, _ := ret[0].(*[]domain.DemandHistory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByCommodityID indicates an expected call of FindByCommodityID.
func (mr *MockDemandHistoryRepositoryMockRecorder) FindByCommodityID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByCommodityID", reflect.TypeOf((*MockDemandHistoryRepository)(nil).FindByCommodityID), ctx, id)
}

// FindByCommodityIDAndRegionID mocks base method.
func (m *MockDemandHistoryRepository) FindByCommodityIDAndRegionID(ctx context.Context, commodityID, regionID uuid.UUID) (*[]domain.DemandHistory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByCommodityIDAndRegionID", ctx, commodityID, regionID)
	ret0, _ := ret[0].(*[]domain.DemandHistory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByCommodityIDAndRegionID indicates an expected call of FindByCommodityIDAndRegionID.
func (mr *MockDemandHistoryRepositoryMockRecorder) FindByCommodityIDAndRegionID(ctx, commodityID, regionID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByCommodityIDAndRegionID", reflect.TypeOf((*MockDemandHistoryRepository)(nil).FindByCommodityIDAndRegionID), ctx, commodityID, regionID)
}

// FindByID mocks base method.
func (m *MockDemandHistoryRepository) FindByID(ctx context.Context, id uuid.UUID) (*domain.DemandHistory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*domain.DemandHistory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockDemandHistoryRepositoryMockRecorder) FindByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockDemandHistoryRepository)(nil).FindByID), ctx, id)
}

// FindByRegionID mocks base method.
func (m *MockDemandHistoryRepository) FindByRegionID(ctx context.Context, id uuid.UUID) (*[]domain.DemandHistory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByRegionID", ctx, id)
	ret0, _ := ret[0].(*[]domain.DemandHistory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByRegionID indicates an expected call of FindByRegionID.
func (mr *MockDemandHistoryRepositoryMockRecorder) FindByRegionID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByRegionID", reflect.TypeOf((*MockDemandHistoryRepository)(nil).FindByRegionID), ctx, id)
}
