// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire_excel

import (
	"github.com/google/wire"
	"github.com/ryvasa/go-super-farmer/cmd/mail/app"
	"github.com/ryvasa/go-super-farmer/pkg/env"
	"github.com/ryvasa/go-super-farmer/pkg/messages"
)

// Injectors from wire.go:

func InitializeExcelApp() (*app.MailApp, error) {
	envEnv, err := env.LoadEnv()
	if err != nil {
		return nil, err
	}
	rabbitMQ, err := messages.NewRabbitMQ(envEnv)
	if err != nil {
		return nil, err
	}
	mailService := app.NewMailService(envEnv)
	mailHandler := app.NewMailHandler(rabbitMQ, mailService)
	mailApp := app.NewApp(envEnv, rabbitMQ, mailHandler)
	return mailApp, nil
}

// wire.go:

var allSet = wire.NewSet(env.LoadEnv, messages.NewRabbitMQ, app.NewMailService, app.NewMailHandler, app.NewApp)
