// Code generated by MockGen. DO NOT EDIT.
// Source: service_api/repository/interface/price_repository_interface.go

// Package mock_repo is a generated GoMock package.
package mock_repo

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
	domain "github.com/ryvasa/go-super-farmer/service_api/model/domain"
	dto "github.com/ryvasa/go-super-farmer/service_api/model/dto"
)

// MockPriceRepository is a mock of PriceRepository interface.
type MockPriceRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPriceRepositoryMockRecorder
}

// MockPriceRepositoryMockRecorder is the mock recorder for MockPriceRepository.
type MockPriceRepositoryMockRecorder struct {
	mock *MockPriceRepository
}

// NewMockPriceRepository creates a new mock instance.
func NewMockPriceRepository(ctrl *gomock.Controller) *MockPriceRepository {
	mock := &MockPriceRepository{ctrl: ctrl}
	mock.recorder = &MockPriceRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPriceRepository) EXPECT() *MockPriceRepositoryMockRecorder {
	return m.recorder
}

// Count mocks base method.
func (m *MockPriceRepository) Count(ctx context.Context, filter *dto.ParamFilterDTO) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", ctx, filter)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockPriceRepositoryMockRecorder) Count(ctx, filter interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockPriceRepository)(nil).Count), ctx, filter)
}

// Create mocks base method.
func (m *MockPriceRepository) Create(ctx context.Context, price *domain.Price) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, price)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockPriceRepositoryMockRecorder) Create(ctx, price interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPriceRepository)(nil).Create), ctx, price)
}

// Delete mocks base method.
func (m *MockPriceRepository) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockPriceRepositoryMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockPriceRepository)(nil).Delete), ctx, id)
}

// FindAll mocks base method.
func (m *MockPriceRepository) FindAll(ctx context.Context, queryParams *dto.PaginationDTO) ([]*domain.Price, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", ctx, queryParams)
	ret0, _ := ret[0].([]*domain.Price)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockPriceRepositoryMockRecorder) FindAll(ctx, queryParams interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockPriceRepository)(nil).FindAll), ctx, queryParams)
}

// FindByCityID mocks base method.
func (m *MockPriceRepository) FindByCityID(ctx context.Context, cityID int64) ([]*domain.Price, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByCityID", ctx, cityID)
	ret0, _ := ret[0].([]*domain.Price)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByCityID indicates an expected call of FindByCityID.
func (mr *MockPriceRepositoryMockRecorder) FindByCityID(ctx, cityID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByCityID", reflect.TypeOf((*MockPriceRepository)(nil).FindByCityID), ctx, cityID)
}

// FindByCommodityID mocks base method.
func (m *MockPriceRepository) FindByCommodityID(ctx context.Context, commodityID uuid.UUID) ([]*domain.Price, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByCommodityID", ctx, commodityID)
	ret0, _ := ret[0].([]*domain.Price)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByCommodityID indicates an expected call of FindByCommodityID.
func (mr *MockPriceRepositoryMockRecorder) FindByCommodityID(ctx, commodityID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByCommodityID", reflect.TypeOf((*MockPriceRepository)(nil).FindByCommodityID), ctx, commodityID)
}

// FindByCommodityIDAndCityID mocks base method.
func (m *MockPriceRepository) FindByCommodityIDAndCityID(ctx context.Context, commodityID uuid.UUID, cityID int64) (*domain.Price, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByCommodityIDAndCityID", ctx, commodityID, cityID)
	ret0, _ := ret[0].(*domain.Price)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByCommodityIDAndCityID indicates an expected call of FindByCommodityIDAndCityID.
func (mr *MockPriceRepositoryMockRecorder) FindByCommodityIDAndCityID(ctx, commodityID, cityID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByCommodityIDAndCityID", reflect.TypeOf((*MockPriceRepository)(nil).FindByCommodityIDAndCityID), ctx, commodityID, cityID)
}

// FindByID mocks base method.
func (m *MockPriceRepository) FindByID(ctx context.Context, id uuid.UUID) (*domain.Price, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*domain.Price)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockPriceRepositoryMockRecorder) FindByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockPriceRepository)(nil).FindByID), ctx, id)
}

// FindDeletedByID mocks base method.
func (m *MockPriceRepository) FindDeletedByID(ctx context.Context, id uuid.UUID) (*domain.Price, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindDeletedByID", ctx, id)
	ret0, _ := ret[0].(*domain.Price)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindDeletedByID indicates an expected call of FindDeletedByID.
func (mr *MockPriceRepositoryMockRecorder) FindDeletedByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindDeletedByID", reflect.TypeOf((*MockPriceRepository)(nil).FindDeletedByID), ctx, id)
}

// Restore mocks base method.
func (m *MockPriceRepository) Restore(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Restore", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Restore indicates an expected call of Restore.
func (mr *MockPriceRepositoryMockRecorder) Restore(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Restore", reflect.TypeOf((*MockPriceRepository)(nil).Restore), ctx, id)
}

// Update mocks base method.
func (m *MockPriceRepository) Update(ctx context.Context, id uuid.UUID, price *domain.Price) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, price)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockPriceRepositoryMockRecorder) Update(ctx, id, price interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockPriceRepository)(nil).Update), ctx, id, price)
}
