package seeders

import (
	"fmt"
	"log"

	"github.com/ryvasa/go-super-farmer/internal/model/domain"
	"gorm.io/gorm"
)

func SeedCities(db *gorm.DB) {
	var count int64
	db.Model(&domain.City{}).Count(&count)
	if count > 0 {
		fmt.Println("City data already seeded")
		return
	}

	cities := []domain.City{
		{ProvinceID: 1, Name: "Kabupaten Aceh Barat"},
		{ProvinceID: 1, Name: "Kabupaten Aceh Barat Daya"},
		{ProvinceID: 1, Name: "Kabupaten Aceh Besar"},
		{ProvinceID: 1, Name: "Kabupaten Aceh Jaya"},
		{ProvinceID: 1, Name: "Kabupaten Aceh Selatan"},
		{ProvinceID: 1, Name: "Kabupaten Aceh Singkil"},
		{ProvinceID: 1, Name: "Kabupaten Aceh Tamiang"},
		{ProvinceID: 1, Name: "Kabupaten Aceh Tengah"},
		{ProvinceID: 1, Name: "Kabupaten Aceh Tenggara"},
		{ProvinceID: 1, Name: "Kabupaten Aceh Timur"},
		{ProvinceID: 1, Name: "Kabupaten Aceh Utara"},
		{ProvinceID: 1, Name: "Kabupaten Bener Meriah"},
		{ProvinceID: 1, Name: "Kabupaten Bireuen"},
		{ProvinceID: 1, Name: "Kabupaten Gayo Lues"},
		{ProvinceID: 1, Name: "Kabupaten Nagan Raya"},
		{ProvinceID: 1, Name: "Kabupaten Pidie"},
		{ProvinceID: 1, Name: "Kabupaten Pidie Jaya"},
		{ProvinceID: 1, Name: "Kabupaten Simeulue"},
		{ProvinceID: 1, Name: "Kota Banda Aceh"},
		{ProvinceID: 1, Name: "Kota Langsa"},
		{ProvinceID: 1, Name: "Kota Lhokseumawe"},
		{ProvinceID: 1, Name: "Kota Sabang"},
		{ProvinceID: 1, Name: "Kota Subulussalam"},
		{ProvinceID: 2, Name: "Kabupaten Asahan"},
		{ProvinceID: 2, Name: "Kabupaten Batubara"},
		{ProvinceID: 2, Name: "Kabupaten Dairi"},
		{ProvinceID: 2, Name: "Kabupaten Deli Serdang"},
		{ProvinceID: 2, Name: "Kabupaten Humbang Hasundutan"},
		{ProvinceID: 2, Name: "Kabupaten Karo"},
		{ProvinceID: 2, Name: "Kabupaten Labuhanbatu"},
		{ProvinceID: 2, Name: "Kabupaten Labuhanbatu Selatan"},
		{ProvinceID: 2, Name: "Kabupaten Labuhanbatu Utara"},
		{ProvinceID: 2, Name: "Kabupaten Langkat"},
		{ProvinceID: 2, Name: "Kabupaten Mandailing Natal"},
		{ProvinceID: 2, Name: "Kabupaten Nias"},
		{ProvinceID: 2, Name: "Kabupaten Nias Barat"},
		{ProvinceID: 2, Name: "Kabupaten Nias Selatan"},
		{ProvinceID: 2, Name: "Kabupaten Nias Utara"},
		{ProvinceID: 2, Name: "Kabupaten Padang Lawas"},
		{ProvinceID: 2, Name: "Kabupaten Padang Lawas Utara"},
		{ProvinceID: 2, Name: "Kabupaten Pakpak Bharat"},
		{ProvinceID: 2, Name: "Kabupaten Samosir"},
		{ProvinceID: 2, Name: "Kabupaten Serdang Bedagai"},
		{ProvinceID: 2, Name: "Kabupaten Simalungun"},
		{ProvinceID: 2, Name: "Kabupaten Tapanuli Selatan"},
		{ProvinceID: 2, Name: "Kabupaten Tapanuli Tengah"},
		{ProvinceID: 2, Name: "Kabupaten Tapanuli Utara"},
		{ProvinceID: 2, Name: "Kabupaten Toba Samosir"},
		{ProvinceID: 2, Name: "Kota Binjai"},
		{ProvinceID: 2, Name: "Kota Gunungsitoli"},
		{ProvinceID: 2, Name: "Kota Medan"},
		{ProvinceID: 2, Name: "Kota Padangsidempuan"},
		{ProvinceID: 2, Name: "Kota Pematangsiantar"},
		{ProvinceID: 2, Name: "Kota Sibolga"},
		{ProvinceID: 2, Name: "Kota Tanjungbalai"},
		{ProvinceID: 2, Name: "Kota Tebing Tinggi"},
		{ProvinceID: 3, Name: "Kabupaten Banyuasin"},
		{ProvinceID: 3, Name: "Kabupaten Empat Lawang"},
		{ProvinceID: 3, Name: "Kabupaten Lahat"},
		{ProvinceID: 3, Name: "Kabupaten Muara Enim"},
		{ProvinceID: 3, Name: "Kabupaten Musi Banyuasin"},
		{ProvinceID: 3, Name: "Kabupaten Musi Rawas"},
		{ProvinceID: 3, Name: "Kabupaten Musi Rawas Utara"},
		{ProvinceID: 3, Name: "Kabupaten Ogan Ilir"},
		{ProvinceID: 3, Name: "Kabupaten Ogan Komering Ilir"},
		{ProvinceID: 3, Name: "Kabupaten Ogan Komering Ulu"},
		{ProvinceID: 3, Name: "Kabupaten Ogan Komering Ulu Selatan"},
		{ProvinceID: 3, Name: "Kabupaten Ogan Komering Ulu Timur"},
		{ProvinceID: 3, Name: "Kabupaten Penukal Abab Lematang Ilir"},
		{ProvinceID: 3, Name: "Kota Lubuklinggau"},
		{ProvinceID: 3, Name: "Kota Pagar Alam"},
		{ProvinceID: 3, Name: "Kota Palembang"},
		{ProvinceID: 3, Name: "Kota Prabumulih"},
		{ProvinceID: 4, Name: "Kabupaten Agam"},
		{ProvinceID: 4, Name: "Kabupaten Dharmasraya"},
		{ProvinceID: 4, Name: "Kabupaten Kepulauan Mentawai"},
		{ProvinceID: 4, Name: "Kabupaten Lima Puluh Kota"},
		{ProvinceID: 4, Name: "Kabupaten Padang Pariaman"},
		{ProvinceID: 4, Name: "Kabupaten Pasaman"},
		{ProvinceID: 4, Name: "Kabupaten Pasaman Barat"},
		{ProvinceID: 4, Name: "Kabupaten Pesisir Selatan"},
		{ProvinceID: 4, Name: "Kabupaten Sijunjung"},
		{ProvinceID: 4, Name: "Kabupaten Solok"},
		{ProvinceID: 4, Name: "Kabupaten Solok Selatan"},
		{ProvinceID: 4, Name: "Kabupaten Tanah Datar"},
		{ProvinceID: 4, Name: "Kota Bukittinggi"},
		{ProvinceID: 4, Name: "Kota Padang"},
		{ProvinceID: 4, Name: "Kota Padangpanjang"},
		{ProvinceID: 4, Name: "Kota Pariaman"},
		{ProvinceID: 4, Name: "Kota Payakumbuh"},
		{ProvinceID: 4, Name: "Kota Sawahlunto"},
		{ProvinceID: 4, Name: "Kota Solok"},
		{ProvinceID: 5, Name: "Kabupaten Bengkulu Selatan"},
		{ProvinceID: 5, Name: "Kabupaten Bengkulu Tengah"},
		{ProvinceID: 5, Name: "Kabupaten Bengkulu Utara"},
		{ProvinceID: 5, Name: "Kabupaten Kaur"},
		{ProvinceID: 5, Name: "Kabupaten Kepahiang"},
		{ProvinceID: 5, Name: "Kabupaten Lebong"},
		{ProvinceID: 5, Name: "Kabupaten Mukomuko"},
		{ProvinceID: 5, Name: "Kabupaten Rejang Lebong"},
		{ProvinceID: 5, Name: "Kabupaten Seluma"},
		{ProvinceID: 5, Name: "Kota Bengkulu"},
		{ProvinceID: 6, Name: "Kabupaten Bengkalis"},
		{ProvinceID: 6, Name: "Kabupaten Indragiri Hilir"},
		{ProvinceID: 6, Name: "Kabupaten Indragiri Hulu"},
		{ProvinceID: 6, Name: "Kabupaten Kampar"},
		{ProvinceID: 6, Name: "Kabupaten Kepulauan Meranti"},
		{ProvinceID: 6, Name: "Kabupaten Kuantan Singingi"},
		{ProvinceID: 6, Name: "Kabupaten Pelalawan"},
		{ProvinceID: 6, Name: "Kabupaten Rokan Hilir"},
		{ProvinceID: 6, Name: "Kabupaten Rokan Hulu"},
		{ProvinceID: 6, Name: "Kabupaten Siak"},
		{ProvinceID: 6, Name: "Kota Dumai"},
		{ProvinceID: 6, Name: "Kota Pekanbaru"},
		{ProvinceID: 7, Name: "Kabupaten Bintan"},
		{ProvinceID: 7, Name: "Kabupaten Karimun"},
		{ProvinceID: 7, Name: "Kabupaten Kepulauan Anambas"},
		{ProvinceID: 7, Name: "Kabupaten Lingga"},
		{ProvinceID: 7, Name: "Kabupaten Natuna"},
		{ProvinceID: 7, Name: "Kota Batam"},
		{ProvinceID: 7, Name: "Kota Tanjung Pinang"},
		{ProvinceID: 8, Name: "Kabupaten Batanghari"},
		{ProvinceID: 8, Name: "Kabupaten Bungo"},
		{ProvinceID: 8, Name: "Kabupaten Kerinci"},
		{ProvinceID: 8, Name: "Kabupaten Merangin"},
		{ProvinceID: 8, Name: "Kabupaten Muaro Jambi"},
		{ProvinceID: 8, Name: "Kabupaten Sarolangun"},
		{ProvinceID: 8, Name: "Kabupaten Tanjung Jabung Barat"},
		{ProvinceID: 8, Name: "Kabupaten Tanjung Jabung Timur"},
		{ProvinceID: 8, Name: "Kabupaten Tebo"},
		{ProvinceID: 8, Name: "Kota Jambi"},
		{ProvinceID: 8, Name: "Kota Sungai Penuh"},
		{ProvinceID: 9, Name: "Kabupaten Lampung Tengah"},
		{ProvinceID: 9, Name: "Kabupaten Lampung Utara"},
		{ProvinceID: 9, Name: "Kabupaten Lampung Selatan"},
		{ProvinceID: 9, Name: "Kabupaten Lampung Barat"},
		{ProvinceID: 9, Name: "Kabupaten Lampung Timur"},
		{ProvinceID: 9, Name: "Kabupaten Mesuji"},
		{ProvinceID: 9, Name: "Kabupaten Pesawaran"},
		{ProvinceID: 9, Name: "Kabupaten Pesisir Barat"},
		{ProvinceID: 9, Name: "Kabupaten Pringsewu"},
		{ProvinceID: 9, Name: "Kabupaten Tulang Bawang"},
		{ProvinceID: 9, Name: "Kabupaten Tulang Bawang Barat"},
		{ProvinceID: 9, Name: "Kabupaten Tanggamus"},
		{ProvinceID: 9, Name: "Kabupaten Way Kanan"},
		{ProvinceID: 9, Name: "Kota Bandar Lampung"},
		{ProvinceID: 9, Name: "Kota Metro"},
		{ProvinceID: 10, Name: "Kabupaten Bangka"},
		{ProvinceID: 10, Name: "Kabupaten Bangka Barat"},
		{ProvinceID: 10, Name: "Kabupaten Bangka Selatan"},
		{ProvinceID: 10, Name: "Kabupaten Bangka Tengah"},
		{ProvinceID: 10, Name: "Kabupaten Belitung"},
		{ProvinceID: 10, Name: "Kabupaten Belitung Timur"},
		{ProvinceID: 10, Name: "Kota Pangkal Pinang"},
		{ProvinceID: 11, Name: "Kabupaten Bengkayang"},
		{ProvinceID: 11, Name: "Kabupaten Kapuas Hulu"},
		{ProvinceID: 11, Name: "Kabupaten Kayong Utara"},
		{ProvinceID: 11, Name: "Kabupaten Ketapang"},
		{ProvinceID: 11, Name: "Kabupaten Kubu Raya"},
		{ProvinceID: 11, Name: "Kabupaten Landak"},
		{ProvinceID: 11, Name: "Kabupaten Melawi"},
		{ProvinceID: 11, Name: "Kabupaten Mempawah"},
		{ProvinceID: 11, Name: "Kabupaten Sambas"},
		{ProvinceID: 11, Name: "Kabupaten Sanggau"},
		{ProvinceID: 11, Name: "Kabupaten Sekadau"},
		{ProvinceID: 11, Name: "Kabupaten Sintang"},
		{ProvinceID: 11, Name: "Kota Pontianak"},
		{ProvinceID: 11, Name: "Kota Singkawang"},
		{ProvinceID: 12, Name: "Kabupaten Berau"},
		{ProvinceID: 12, Name: "Kabupaten Kutai Barat"},
		{ProvinceID: 12, Name: "Kabupaten Kutai Kartanegara"},
		{ProvinceID: 12, Name: "Kabupaten Kutai Timur"},
		{ProvinceID: 12, Name: "Kabupaten Mahakam Ulu"},
		{ProvinceID: 12, Name: "Kabupaten Paser"},
		{ProvinceID: 12, Name: "Kabupaten Penajam Paser Utara"},
		{ProvinceID: 12, Name: "Kota Balikpapan"},
		{ProvinceID: 12, Name: "Kota Bontang"},
		{ProvinceID: 12, Name: "Kota Samarinda"},
		{ProvinceID: 14, Name: "Kabupaten Balangan"},
		{ProvinceID: 14, Name: "Kabupaten Banjar"},
		{ProvinceID: 14, Name: "Kabupaten Barito Kuala"},
		{ProvinceID: 14, Name: "Kabupaten Hulu Sungai Selatan"},
		{ProvinceID: 14, Name: "Kabupaten Hulu Sungai Tengah"},
		{ProvinceID: 14, Name: "Kabupaten Hulu Sungai Utara"},
		{ProvinceID: 14, Name: "Kabupaten Kotabaru"},
		{ProvinceID: 14, Name: "Kabupaten Tabalong"},
		{ProvinceID: 14, Name: "Kabupaten Tanah Bumbu"},
		{ProvinceID: 14, Name: "Kabupaten Tanah Laut"},
		{ProvinceID: 14, Name: "Kabupaten Tapin"},
		{ProvinceID: 14, Name: "Kota Banjarbaru"},
		{ProvinceID: 14, Name: "Kota Banjarmasin"},
		{ProvinceID: 14, Name: "Kabupaten Barito Selatan"},
		{ProvinceID: 14, Name: "Kabupaten Barito Timur"},
		{ProvinceID: 14, Name: "Kabupaten Barito Utara"},
		{ProvinceID: 14, Name: "Kabupaten Gunung Mas"},
		{ProvinceID: 14, Name: "Kabupaten Kapuas"},
		{ProvinceID: 14, Name: "Kabupaten Katingan"},
		{ProvinceID: 14, Name: "Kabupaten Kotawaringin Barat"},
		{ProvinceID: 14, Name: "Kabupaten Kotawaringin Timur"},
		{ProvinceID: 14, Name: "Kabupaten Lamandau"},
		{ProvinceID: 14, Name: "Kabupaten Murung Raya"},
		{ProvinceID: 14, Name: "Kabupaten Pulang Pisau"},
		{ProvinceID: 14, Name: "Kabupaten Sukamara"},
		{ProvinceID: 14, Name: "Kabupaten Seruyan"},
		{ProvinceID: 14, Name: "Kota Palangka Raya"},
		{ProvinceID: 15, Name: "Kabupaten Bulungan"},
		{ProvinceID: 15, Name: "Kabupaten Malinau"},
		{ProvinceID: 15, Name: "Kabupaten Nunukan"},
		{ProvinceID: 15, Name: "Kabupaten Tana Tidung"},
		{ProvinceID: 15, Name: "Kota Tarakan"},
		{ProvinceID: 16, Name: "Kabupaten Lebak"},
		{ProvinceID: 16, Name: "Kabupaten Pandeglang"},
		{ProvinceID: 16, Name: "Kabupaten Serang"},
		{ProvinceID: 16, Name: "Kabupaten Tangerang"},
		{ProvinceID: 16, Name: "Kota Cilegon"},
		{ProvinceID: 16, Name: "Kota Serang"},
		{ProvinceID: 16, Name: "Kota Tangerang"},
		{ProvinceID: 16, Name: "Kota Tangerang Selatan"},
		{ProvinceID: 17, Name: "Kota Administrasi Jakarta Barat"},
		{ProvinceID: 17, Name: "Kota Administrasi Jakarta Pusat"},
		{ProvinceID: 17, Name: "Kota Administrasi Jakarta Selatan"},
		{ProvinceID: 17, Name: "Kota Administrasi Jakarta Timur"},
		{ProvinceID: 17, Name: "Kota Administrasi Jakarta Utara"},
		{ProvinceID: 17, Name: "Kabupaten Administrasi Kepulauan Seribu"},
		{ProvinceID: 18, Name: "Kabupaten Bandung"},
		{ProvinceID: 18, Name: "Kabupaten Bandung Barat"},
		{ProvinceID: 18, Name: "Kabupaten Bekasi"},
		{ProvinceID: 18, Name: "Kabupaten Bogor"},
		{ProvinceID: 18, Name: "Kabupaten Ciamis"},
		{ProvinceID: 18, Name: "Kabupaten Cianjur"},
		{ProvinceID: 18, Name: "Kabupaten Cirebon"},
		{ProvinceID: 18, Name: "Kabupaten Garut"},
		{ProvinceID: 18, Name: "Kabupaten Indramayu"},
		{ProvinceID: 18, Name: "Kabupaten Karawang"},
		{ProvinceID: 18, Name: "Kabupaten Kuningan"},
		{ProvinceID: 18, Name: "Kabupaten Majalengka"},
		{ProvinceID: 18, Name: "Kabupaten Pangandaran"},
		{ProvinceID: 18, Name: "Kabupaten Purwakarta"},
		{ProvinceID: 18, Name: "Kabupaten Subang"},
		{ProvinceID: 18, Name: "Kabupaten Sukabumi"},
		{ProvinceID: 18, Name: "Kabupaten Sumedang"},
		{ProvinceID: 18, Name: "Kabupaten Tasikmalaya"},
		{ProvinceID: 18, Name: "Kota Bandung"},
		{ProvinceID: 18, Name: "Kota Banjar"},
		{ProvinceID: 18, Name: "Kota Bekasi"},
		{ProvinceID: 18, Name: "Kota Bogor"},
		{ProvinceID: 18, Name: "Kota Cimahi"},
		{ProvinceID: 18, Name: "Kota Cirebon"},
		{ProvinceID: 18, Name: "Kota Depok"},
		{ProvinceID: 18, Name: "Kota Sukabumi"},
		{ProvinceID: 18, Name: "Kota Tasikmalaya"},
		{ProvinceID: 19, Name: "Kabupaten Banjarnegara"},
		{ProvinceID: 19, Name: "Kabupaten Banyumas"},
		{ProvinceID: 19, Name: "Kabupaten Batang"},
		{ProvinceID: 19, Name: "Kabupaten Blora"},
		{ProvinceID: 19, Name: "Kabupaten Boyolali"},
		{ProvinceID: 19, Name: "Kabupaten Brebes"},
		{ProvinceID: 19, Name: "Kabupaten Cilacap"},
		{ProvinceID: 19, Name: "Kabupaten Demak"},
		{ProvinceID: 19, Name: "Kabupaten Grobogan"},
		{ProvinceID: 19, Name: "Kabupaten Jepara"},
		{ProvinceID: 19, Name: "Kabupaten Karanganyar"},
		{ProvinceID: 19, Name: "Kabupaten Kebumen"},
		{ProvinceID: 19, Name: "Kabupaten Kendal"},
		{ProvinceID: 19, Name: "Kabupaten Klaten"},
		{ProvinceID: 19, Name: "Kabupaten Kudus"},
		{ProvinceID: 19, Name: "Kabupaten Magelang"},
		{ProvinceID: 19, Name: "Kabupaten Pati"},
		{ProvinceID: 19, Name: "Kabupaten Pekalongan"},
		{ProvinceID: 19, Name: "Kabupaten Pemalang"},
		{ProvinceID: 19, Name: "Kabupaten Purbalingga"},
		{ProvinceID: 19, Name: "Kabupaten Purworejo"},
		{ProvinceID: 19, Name: "Kabupaten Rembang"},
		{ProvinceID: 19, Name: "Kabupaten Semarang"},
		{ProvinceID: 19, Name: "Kabupaten Sragen"},
		{ProvinceID: 19, Name: "Kabupaten Sukoharjo"},
		{ProvinceID: 19, Name: "Kabupaten Tegal"},
		{ProvinceID: 19, Name: "Kabupaten Temanggung"},
		{ProvinceID: 19, Name: "Kabupaten Wonogiri"},
		{ProvinceID: 19, Name: "Kabupaten Wonosobo"},
		{ProvinceID: 19, Name: "Kota Magelang"},
		{ProvinceID: 19, Name: "Kota Pekalongan"},
		{ProvinceID: 19, Name: "Kota Salatiga"},
		{ProvinceID: 19, Name: "Kota Semarang"},
		{ProvinceID: 19, Name: "Kota Surakarta"},
		{ProvinceID: 19, Name: "Kota Tegal"},
		{ProvinceID: 20, Name: "Kabupaten Bantul"},
		{ProvinceID: 20, Name: "Kabupaten Gunungkidul"},
		{ProvinceID: 20, Name: "Kabupaten Kulon Progo"},
		{ProvinceID: 20, Name: "Kabupaten Sleman"},
		{ProvinceID: 20, Name: "Kota Yogyakarta"},
		{ProvinceID: 21, Name: "Kabupaten Bangkalan"},
		{ProvinceID: 21, Name: "Kabupaten Banyuwangi"},
		{ProvinceID: 21, Name: "Kabupaten Blitar"},
		{ProvinceID: 21, Name: "Kabupaten Bojonegoro"},
		{ProvinceID: 21, Name: "Kabupaten Bondowoso"},
		{ProvinceID: 21, Name: "Kabupaten Gresik"},
		{ProvinceID: 21, Name: "Kabupaten Jember"},
		{ProvinceID: 21, Name: "Kabupaten Jombang"},
		{ProvinceID: 21, Name: "Kabupaten Kediri"},
		{ProvinceID: 21, Name: "Kabupaten Lamongan"},
		{ProvinceID: 21, Name: "Kabupaten Lumajang"},
		{ProvinceID: 21, Name: "Kabupaten Madiun"},
		{ProvinceID: 21, Name: "Kabupaten Magetan"},
		{ProvinceID: 21, Name: "Kabupaten Malang"},
		{ProvinceID: 21, Name: "Kabupaten Mojokerto"},
		{ProvinceID: 21, Name: "Kabupaten Nganjuk"},
		{ProvinceID: 21, Name: "Kabupaten Ngawi"},
		{ProvinceID: 21, Name: "Kabupaten Pacitan"},
		{ProvinceID: 21, Name: "Kabupaten Pamekasan"},
		{ProvinceID: 21, Name: "Kabupaten Pasuruan"},
		{ProvinceID: 21, Name: "Kabupaten Ponorogo"},
		{ProvinceID: 21, Name: "Kabupaten Probolinggo"},
		{ProvinceID: 21, Name: "Kabupaten Sampang"},
		{ProvinceID: 21, Name: "Kabupaten Sidoarjo"},
		{ProvinceID: 21, Name: "Kabupaten Situbondo"},
		{ProvinceID: 21, Name: "Kabupaten Sumenep"},
		{ProvinceID: 21, Name: "Kabupaten Trenggalek"},
		{ProvinceID: 21, Name: "Kabupaten Tuban"},
		{ProvinceID: 21, Name: "Kabupaten Tulungagung"},
		{ProvinceID: 21, Name: "Kota Batu"},
		{ProvinceID: 21, Name: "Kota Blitar"},
		{ProvinceID: 21, Name: "Kota Kediri"},
		{ProvinceID: 21, Name: "Kota Madiun"},
		{ProvinceID: 21, Name: "Kota Malang"},
		{ProvinceID: 21, Name: "Kota Mojokerto"},
		{ProvinceID: 21, Name: "Kota Pasuruan"},
		{ProvinceID: 21, Name: "Kota Probolinggo"},
		{ProvinceID: 21, Name: "Kota Surabaya"},
		{ProvinceID: 22, Name: "Kabupaten Badung"},
		{ProvinceID: 22, Name: "Kabupaten Bangli"},
		{ProvinceID: 22, Name: "Kabupaten Buleleng"},
		{ProvinceID: 22, Name: "Kabupaten Gianyar"},
		{ProvinceID: 22, Name: "Kabupaten Jembrana"},
		{ProvinceID: 22, Name: "Kabupaten Karangasem"},
		{ProvinceID: 22, Name: "Kabupaten Klungkung"},
		{ProvinceID: 22, Name: "Kabupaten Tabanan"},
		{ProvinceID: 22, Name: "Kota Denpasar"},
		{ProvinceID: 23, Name: "Kabupaten Alor"},
		{ProvinceID: 23, Name: "Kabupaten Belu"},
		{ProvinceID: 23, Name: "Kabupaten Ende"},
		{ProvinceID: 23, Name: "Kabupaten Flores Timur"},
		{ProvinceID: 23, Name: "Kabupaten Kupang"},
		{ProvinceID: 23, Name: "Kabupaten Lembata"},
		{ProvinceID: 23, Name: "Kabupaten Malaka"},
		{ProvinceID: 23, Name: "Kabupaten Manggarai"},
		{ProvinceID: 23, Name: "Kabupaten Manggarai Barat"},
		{ProvinceID: 23, Name: "Kabupaten Manggarai Timur"},
		{ProvinceID: 23, Name: "Kabupaten Ngada"},
		{ProvinceID: 23, Name: "Kabupaten Nagekeo"},
		{ProvinceID: 23, Name: "Kabupaten Rote Ndao"},
		{ProvinceID: 23, Name: "Kabupaten Sabu Raijua"},
		{ProvinceID: 23, Name: "Kabupaten Sikka"},
		{ProvinceID: 23, Name: "Kabupaten Sumba Barat"},
		{ProvinceID: 23, Name: "Kabupaten Sumba Barat Daya"},
		{ProvinceID: 23, Name: "Kabupaten Sumba Tengah"},
		{ProvinceID: 23, Name: "Kabupaten Sumba Timur"},
		{ProvinceID: 23, Name: "Kabupaten Timor Tengah Selatan"},
		{ProvinceID: 23, Name: "Kabupaten Timor Tengah Utara"},
		{ProvinceID: 23, Name: "Kota Kupang"},
		{ProvinceID: 24, Name: "Kabupaten Bima"},
		{ProvinceID: 24, Name: "Kabupaten Dompu"},
		{ProvinceID: 24, Name: "Kabupaten Lombok Barat"},
		{ProvinceID: 24, Name: "Kabupaten Lombok Tengah"},
		{ProvinceID: 24, Name: "Kabupaten Lombok Timur"},
		{ProvinceID: 24, Name: "Kabupaten Lombok Utara"},
		{ProvinceID: 24, Name: "Kabupaten Sumbawa"},
		{ProvinceID: 24, Name: "Kabupaten Sumbawa Barat"},
		{ProvinceID: 24, Name: "Kota Bima"},
		{ProvinceID: 24, Name: "Kota Mataram"},
		{ProvinceID: 25, Name: "Kabupaten Boalemo"},
		{ProvinceID: 25, Name: "Kabupaten Bone Bolango"},
		{ProvinceID: 25, Name: "Kabupaten Gorontalo"},
		{ProvinceID: 25, Name: "Kabupaten Gorontalo Utara"},
		{ProvinceID: 25, Name: "Kabupaten Pohuwato"},
		{ProvinceID: 25, Name: "Kota Gorontalo"},
		{ProvinceID: 26, Name: "Kabupaten Majene"},
		{ProvinceID: 26, Name: "Kabupaten Mamasa"},
		{ProvinceID: 26, Name: "Kabupaten Mamuju"},
		{ProvinceID: 26, Name: "Kabupaten Mamuju Tengah"},
		{ProvinceID: 26, Name: "Kabupaten Mamuju Utara"},
		{ProvinceID: 26, Name: "Kabupaten Polewali Mandar"},
		{ProvinceID: 26, Name: "Kota Mamuju"},
		{ProvinceID: 27, Name: "Kabupaten Banggai"},
		{ProvinceID: 27, Name: "Kabupaten Banggai Kepulauan"},
		{ProvinceID: 27, Name: "Kabupaten Banggai Laut"},
		{ProvinceID: 27, Name: "Kabupaten Buol"},
		{ProvinceID: 27, Name: "Kabupaten Donggala"},
		{ProvinceID: 27, Name: "Kabupaten Morowali"},
		{ProvinceID: 27, Name: "Kabupaten Morowali Utara"},
		{ProvinceID: 27, Name: "Kabupaten Parigi Moutong"},
		{ProvinceID: 27, Name: "Kabupaten Poso"},
		{ProvinceID: 27, Name: "Kabupaten Sigi"},
		{ProvinceID: 27, Name: "Kabupaten Tojo Una-Una"},
		{ProvinceID: 27, Name: "Kabupaten Toli-Toli"},
		{ProvinceID: 27, Name: "Kota Palu"},
		{ProvinceID: 28, Name: "Kabupaten Bolaang Mongondow"},
		{ProvinceID: 28, Name: "Kabupaten Bolaang Mongondow Selatan"},
		{ProvinceID: 28, Name: "Kabupaten Bolaang Mongondow Timur"},
		{ProvinceID: 28, Name: "Kabupaten Bolaang Mongondow Utara"},
		{ProvinceID: 28, Name: "Kabupaten Kepulauan Sangihe"},
		{ProvinceID: 28, Name: "Kabupaten Kepulauan Siau Tagulandang Biaro"},
		{ProvinceID: 28, Name: "Kabupaten Kepulauan Talaud"},
		{ProvinceID: 28, Name: "Kabupaten Minahasa"},
		{ProvinceID: 28, Name: "Kabupaten Minahasa Selatan"},
		{ProvinceID: 28, Name: "Kabupaten Minahasa Tenggara"},
		{ProvinceID: 28, Name: "Kabupaten Minahasa Utara"},
		{ProvinceID: 28, Name: "Kota Bitung"},
		{ProvinceID: 28, Name: "Kota Kotamobagu"},
		{ProvinceID: 28, Name: "Kota Manado"},
		{ProvinceID: 28, Name: "Kota Tomohon"},
		{ProvinceID: 29, Name: "Kabupaten Bombana"},
		{ProvinceID: 29, Name: "Kabupaten Buton"},
		{ProvinceID: 29, Name: "Kabupaten Buton Selatan"},
		{ProvinceID: 29, Name: "Kabupaten Buton Tengah"},
		{ProvinceID: 29, Name: "Kabupaten Buton Utara"},
		{ProvinceID: 29, Name: "Kabupaten Kolaka"},
		{ProvinceID: 29, Name: "Kabupaten Kolaka Timur"},
		{ProvinceID: 29, Name: "Kabupaten Kolaka Utara"},
		{ProvinceID: 29, Name: "Kabupaten Konawe"},
		{ProvinceID: 29, Name: "Kabupaten Konawe Kepulauan"},
		{ProvinceID: 29, Name: "Kabupaten Konawe Selatan"},
		{ProvinceID: 29, Name: "Kabupaten Konawe Utara"},
		{ProvinceID: 29, Name: "Kabupaten Muna"},
		{ProvinceID: 29, Name: "Kabupaten Muna Barat"},
		{ProvinceID: 29, Name: "Kabupaten Wakatobi"},
		{ProvinceID: 29, Name: "Kota Bau-Bau"},
		{ProvinceID: 29, Name: "Kota Kendari"},
		{ProvinceID: 30, Name: "Kabupaten Bantaeng"},
		{ProvinceID: 30, Name: "Kabupaten Barru"},
		{ProvinceID: 30, Name: "Kabupaten Bone"},
		{ProvinceID: 30, Name: "Kabupaten Bulukumba"},
		{ProvinceID: 30, Name: "Kabupaten Enrekang"},
		{ProvinceID: 30, Name: "Kabupaten Gowa"},
		{ProvinceID: 30, Name: "Kabupaten Jeneponto"},
		{ProvinceID: 30, Name: "Kabupaten Kepulauan Selayar"},
		{ProvinceID: 30, Name: "Kabupaten Luwu"},
		{ProvinceID: 30, Name: "Kabupaten Luwu Timur"},
		{ProvinceID: 30, Name: "Kabupaten Luwu Utara"},
		{ProvinceID: 30, Name: "Kabupaten Maros"},
		{ProvinceID: 30, Name: "Kabupaten Pangkajene dan Kepulauan"},
		{ProvinceID: 30, Name: "Kabupaten Pinrang"},
		{ProvinceID: 30, Name: "Kabupaten Sidenreng Rappang"},
		{ProvinceID: 30, Name: "Kabupaten Sinjai"},
		{ProvinceID: 30, Name: "Kabupaten Soppeng"},
		{ProvinceID: 30, Name: "Kabupaten Takalar"},
		{ProvinceID: 30, Name: "Kabupaten Tana Toraja"},
		{ProvinceID: 30, Name: "Kabupaten Toraja Utara"},
		{ProvinceID: 30, Name: "Kabupaten Wajo"},
		{ProvinceID: 30, Name: "Kota Makassar"},
		{ProvinceID: 30, Name: "Kota Palopo"},
		{ProvinceID: 30, Name: "Kota Parepare"},
		{ProvinceID: 31, Name: "Kabupaten Halmahera Barat"},
		{ProvinceID: 31, Name: "Kabupaten Halmahera Tengah"},
		{ProvinceID: 31, Name: "Kabupaten Halmahera Utara"},
		{ProvinceID: 31, Name: "Kabupaten Halmahera Selatan"},
		{ProvinceID: 31, Name: "Kabupaten Kepulauan Sula"},
		{ProvinceID: 31, Name: "Kabupaten Halmahera Timur"},
		{ProvinceID: 31, Name: "Kabupaten Pulau Morotai"},
		{ProvinceID: 31, Name: "Kabupaten Pulau Taliabu"},
		{ProvinceID: 31, Name: "Kota Ternate"},
		{ProvinceID: 31, Name: "Kota Tidore Kepulauan"},
		{ProvinceID: 32, Name: "Kabupaten Buru"},
		{ProvinceID: 32, Name: "Kabupaten Buru Selatan"},
		{ProvinceID: 32, Name: "Kabupaten Kepulauan Aru"},
		{ProvinceID: 32, Name: "Kabupaten Maluku Barat Daya"},
		{ProvinceID: 32, Name: "Kabupaten Maluku Tengah"},
		{ProvinceID: 32, Name: "Kabupaten Maluku Tenggara"},
		{ProvinceID: 32, Name: "Kabupaten Maluku Tenggara Barat"},
		{ProvinceID: 32, Name: "Kabupaten Seram Bagian Barat"},
		{ProvinceID: 32, Name: "Kabupaten Seram Bagian Timur"},
		{ProvinceID: 32, Name: "Kota Ambon"},
		{ProvinceID: 32, Name: "Kota Tual"},
		{ProvinceID: 33, Name: "Kabupaten Fakfak"},
		{ProvinceID: 33, Name: "Kabupaten Kaimana"},
		{ProvinceID: 33, Name: "Kabupaten Manokwari"},
		{ProvinceID: 33, Name: "Kabupaten Manokwari Selatan"},
		{ProvinceID: 33, Name: "Kabupaten Pegunungan Arfak"},
		{ProvinceID: 33, Name: "Kabupaten Teluk Bintuni"},
		{ProvinceID: 33, Name: "Kabupaten Teluk Wondama"},
		{ProvinceID: 33, Name: "Kota Sorong"},
		{ProvinceID: 34, Name: "Kabupaten Biak Numfor"},
		{ProvinceID: 34, Name: "Kabupaten Jayapura"},
		{ProvinceID: 34, Name: "Kabupaten Keerom"},
		{ProvinceID: 34, Name: "Kabupaten Kepulauan Yapen"},
		{ProvinceID: 34, Name: "Kabupaten Mamberamo Raya"},
		{ProvinceID: 34, Name: "Kabupaten Mamberamo Tengah"},
		{ProvinceID: 34, Name: "Kabupaten Sarmi"},
		{ProvinceID: 34, Name: "Kabupaten Supiori"},
		{ProvinceID: 34, Name: "Kabupaten Tolikara"},
		{ProvinceID: 34, Name: "Kabupaten Waropen"},
		{ProvinceID: 34, Name: "Kota Jayapura"},
		{ProvinceID: 35, Name: "Kabupaten Deiyai"},
		{ProvinceID: 35, Name: "Kabupaten Dogiyai"},
		{ProvinceID: 35, Name: "Kabupaten Intan Jaya"},
		{ProvinceID: 35, Name: "Kabupaten Nabire"},
		{ProvinceID: 35, Name: "Kabupaten Paniai"},
		{ProvinceID: 35, Name: "Kabupaten Puncak"},
		{ProvinceID: 35, Name: "Kabupaten Puncak Jaya"},
		{ProvinceID: 35, Name: "Kabupaten Mimika"},
		{ProvinceID: 36, Name: "Kabupaten Jayawijaya"},
		{ProvinceID: 36, Name: "Kabupaten Lanny Jaya"},
		{ProvinceID: 36, Name: "Kabupaten Mamberamo Tengah"},
		{ProvinceID: 36, Name: "Kabupaten Nduga"},
		{ProvinceID: 36, Name: "Kabupaten Pegunungan Bintang"},
		{ProvinceID: 36, Name: "Kabupaten Yahukimo"},
		{ProvinceID: 36, Name: "Kabupaten Yalimo"},
		{ProvinceID: 37, Name: "Kabupaten Asmat"},
		{ProvinceID: 37, Name: "Kabupaten Boven Digoel"},
		{ProvinceID: 37, Name: "Kabupaten Mappi"},
		{ProvinceID: 37, Name: "Kabupaten Merauke"},
		{ProvinceID: 38, Name: "Kabupaten Maybrat"},
		{ProvinceID: 38, Name: "Kabupaten Raja Ampat"},
		{ProvinceID: 38, Name: "Kabupaten Sorong"},
		{ProvinceID: 38, Name: "Kabupaten Sorong Selatan"},
		{ProvinceID: 38, Name: "Kabupaten Tambrauw"},
		{ProvinceID: 38, Name: "Kota Sorong"},
	}

	for _, city := range cities {
		result := db.Create(&city)
		if result.Error != nil {
			log.Fatalf("error seeding data City: %v", result.Error)
		}
	}

	fmt.Println("City data seeded successfully")
}
