package seeders

import (
	"log"

	"github.com/brianvoe/gofakeit/v6"
	"github.com/google/uuid"
	"github.com/ryvasa/go-super-farmer/internal/model/domain"
	"github.com/ryvasa/go-super-farmer/utils"
)

var cities = []*domain.City{
	// Kota dan Kabupaten di Provinsi Nanggroe Aceh Darussalam
	{ID: 1, Name: "Kabupaten Aceh Barat", ProvinceID: 1},
	{ID: 2, Name: "Kabupaten Aceh Besar", ProvinceID: 1},
	{ID: 3, Name: "Kabupaten Aceh Jaya", ProvinceID: 1},
	{ID: 4, Name: "Kabupaten Aceh Selatan", ProvinceID: 1},
	{ID: 5, Name: "Kabupaten Aceh Singkil", ProvinceID: 1},
	{ID: 6, Name: "Kabupaten Aceh Tamiang", ProvinceID: 1},
	{ID: 7, Name: "Kabupaten Aceh Tengah", ProvinceID: 1},
	{ID: 8, Name: "Kabupaten Aceh Tenggara", ProvinceID: 1},
	{ID: 9, Name: "Kabupaten Aceh Timur", ProvinceID: 1},
	{ID: 10, Name: "Kabupaten Aceh Utara", ProvinceID: 1},
	{ID: 11, Name: "Kabupaten Bener Meriah", ProvinceID: 1},
	{ID: 12, Name: "Kabupaten Bireuen", ProvinceID: 1},
	{ID: 13, Name: "Kabupaten Gayo Lues", ProvinceID: 1},
	{ID: 14, Name: "Kabupaten Nagan Raya", ProvinceID: 1},
	{ID: 15, Name: "Kabupaten Pidie", ProvinceID: 1},
	{ID: 16, Name: "Kabupaten Pidie Jaya", ProvinceID: 1},
	{ID: 17, Name: "Kabupaten Simeulue", ProvinceID: 1},
	{ID: 18, Name: "Kota Banda Aceh", ProvinceID: 1},
	{ID: 19, Name: "Kota Langsa", ProvinceID: 1},
	{ID: 20, Name: "Kota Lhokseumawe", ProvinceID: 1},
	{ID: 21, Name: "Kota Sabang", ProvinceID: 1},
	{ID: 22, Name: "Kota Subulussalam", ProvinceID: 1},

	// Kota dan Kabupaten di Provinsi Sumatera Utara
	{ID: 23, Name: "Kabupaten Asahan", ProvinceID: 2},
	{ID: 24, Name: "Kabupaten Batu Bara", ProvinceID: 2},
	{ID: 25, Name: "Kabupaten Dairi", ProvinceID: 2},
	{ID: 26, Name: "Kabupaten Deli Serdang", ProvinceID: 2},
	{ID: 27, Name: "Kabupaten Humbang Hasundutan", ProvinceID: 2},
	{ID: 28, Name: "Kabupaten Karo", ProvinceID: 2},
	{ID: 29, Name: "Kabupaten Labuhanbatu", ProvinceID: 2},
	{ID: 30, Name: "Kabupaten Labuhanbatu Selatan", ProvinceID: 2},
	{ID: 31, Name: "Kabupaten Labuhanbatu Utara", ProvinceID: 2},
	{ID: 32, Name: "Kabupaten Langkat", ProvinceID: 2},
	{ID: 33, Name: "Kabupaten Mandailing Natal", ProvinceID: 2},
	{ID: 34, Name: "Kabupaten Nias", ProvinceID: 2},
	{ID: 35, Name: "Kabupaten Nias Barat", ProvinceID: 2},
	{ID: 36, Name: "Kabupaten Nias Selatan", ProvinceID: 2},
	{ID: 37, Name: "Kabupaten Nias Utara", ProvinceID: 2},
	{ID: 38, Name: "Kabupaten Padang Lawas", ProvinceID: 2},
	{ID: 39, Name: "Kabupaten Padang Lawas Utara", ProvinceID: 2},
	{ID: 40, Name: "Kabupaten Pakpak Bharat", ProvinceID: 2},
	{ID: 41, Name: "Kabupaten Samosir", ProvinceID: 2},
	{ID: 42, Name: "Kabupaten Serdang Bedagai", ProvinceID: 2},
	{ID: 43, Name: "Kabupaten Simalungun", ProvinceID: 2},
	{ID: 44, Name: "Kabupaten Tapanuli Selatan", ProvinceID: 2},
	{ID: 45, Name: "Kabupaten Tapanuli Tengah", ProvinceID: 2},
	{ID: 46, Name: "Kabupaten Tapanuli Utara", ProvinceID: 2},
	{ID: 47, Name: "Kabupaten Toba", ProvinceID: 2},
	{ID: 48, Name: "Kota Binjai", ProvinceID: 2},
	{ID: 49, Name: "Kota Gunungsitoli", ProvinceID: 2},
	{ID: 50, Name: "Kota Medan", ProvinceID: 2},
	{ID: 51, Name: "Kota Padangsidempuan", ProvinceID: 2},
	{ID: 52, Name: "Kota Pematangsiantar", ProvinceID: 2},
	{ID: 53, Name: "Kota Sibolga", ProvinceID: 2},
	{ID: 54, Name: "Kota Tanjungbalai", ProvinceID: 2},
	{ID: 55, Name: "Kota Tebing Tinggi", ProvinceID: 2},

	// Kota dan kabupaten di Provinsi Sumatra Barat
	{ID: 56, Name: "Kabupaten Agam", ProvinceID: 3},
	{ID: 57, Name: "Kabupaten Dharmasraya", ProvinceID: 3},
	{ID: 58, Name: "Kabupaten Kepulauan Mentawai", ProvinceID: 3},
	{ID: 59, Name: "Kabupaten Lima Puluh Kota", ProvinceID: 3},
	{ID: 60, Name: "Kabupaten Padang Pariaman", ProvinceID: 3},
	{ID: 61, Name: "Kabupaten Pasaman", ProvinceID: 3},
	{ID: 62, Name: "Kabupaten Pasaman Barat", ProvinceID: 3},
	{ID: 63, Name: "Kabupaten Pesisir Selatan", ProvinceID: 3},
	{ID: 64, Name: "Kabupaten Sijunjung", ProvinceID: 3},
	{ID: 65, Name: "Kabupaten Solok", ProvinceID: 3},
	{ID: 66, Name: "Kabupaten Solok Selatan", ProvinceID: 3},
	{ID: 67, Name: "Kabupaten Tanah Datar", ProvinceID: 3},
	{ID: 68, Name: "Kota Bukittinggi", ProvinceID: 3},
	{ID: 69, Name: "Kota Padang", ProvinceID: 3},
	{ID: 70, Name: "Kota Padang Panjang", ProvinceID: 3},
	{ID: 71, Name: "Kota Pariaman", ProvinceID: 3},
	{ID: 72, Name: "Kota Payakumbuh", ProvinceID: 3},
	{ID: 73, Name: "Kota Sawahlunto", ProvinceID: 3},
	{ID: 74, Name: "Kota Solok", ProvinceID: 3},

	// Kota dan kabupaten di Provinsi Riau
	{ID: 75, Name: "Kabupaten Bengkalis", ProvinceID: 4},
	{ID: 76, Name: "Kabupaten Indragiri Hilir", ProvinceID: 4},
	{ID: 77, Name: "Kabupaten Indragiri Hulu", ProvinceID: 4},
	{ID: 78, Name: "Kabupaten Kampar", ProvinceID: 4},
	{ID: 79, Name: "Kabupaten Kepulauan Meranti", ProvinceID: 4},
	{ID: 80, Name: "Kabupaten Kuantan Singingi", ProvinceID: 4},
	{ID: 81, Name: "Kabupaten Pelalawan", ProvinceID: 4},
	{ID: 82, Name: "Kabupaten Rokan Hilir", ProvinceID: 4},
	{ID: 83, Name: "Kabupaten Rokan Hulu", ProvinceID: 4},
	{ID: 84, Name: "Kabupaten Siak", ProvinceID: 4},
	{ID: 85, Name: "Kota Dumai", ProvinceID: 4},
	{ID: 86, Name: "Kota Pekanbaru", ProvinceID: 4},

	// Kota dan kabupaten di Provinsi Jambi
	{ID: 87, Name: "Kabupaten Batanghari", ProvinceID: 5},
	{ID: 88, Name: "Kabupaten Bungo", ProvinceID: 5},
	{ID: 89, Name: "Kabupaten Kerinci", ProvinceID: 5},
	{ID: 90, Name: "Kabupaten Merangin", ProvinceID: 5},
	{ID: 91, Name: "Kabupaten Muaro Jambi", ProvinceID: 5},
	{ID: 92, Name: "Kabupaten Sarolangun", ProvinceID: 5},
	{ID: 93, Name: "Kabupaten Tanjung Jabung Barat", ProvinceID: 5},
	{ID: 94, Name: "Kabupaten Tanjung Jabung Timur", ProvinceID: 5},
	{ID: 95, Name: "Kabupaten Tebo", ProvinceID: 5},
	{ID: 96, Name: "Kota Jambi", ProvinceID: 5},
	{ID: 97, Name: "Kota Sungai Penuh", ProvinceID: 5},

	// Kota dan kabupaten di Provinsi Sumatra Selatan
	{ID: 98, Name: "Kabupaten Banyuasin", ProvinceID: 6},
	{ID: 99, Name: "Kabupaten Empat Lawang", ProvinceID: 6},
	{ID: 100, Name: "Kabupaten Lahat", ProvinceID: 6},
	{ID: 101, Name: "Kabupaten Muara Enim", ProvinceID: 6},
	{ID: 102, Name: "Kabupaten Musi Banyuasin", ProvinceID: 6},
	{ID: 103, Name: "Kabupaten Musi Rawas", ProvinceID: 6},
	{ID: 104, Name: "Kabupaten Musi Rawas Utara", ProvinceID: 6},
	{ID: 105, Name: "Kabupaten Ogan Ilir", ProvinceID: 6},
	{ID: 106, Name: "Kabupaten Ogan Komering Ilir", ProvinceID: 6},
	{ID: 107, Name: "Kabupaten Ogan Komering Ulu", ProvinceID: 6},
	{ID: 108, Name: "Kabupaten Ogan Komering Ulu Selatan", ProvinceID: 6},
	{ID: 109, Name: "Kabupaten Ogan Komering Ulu Timur", ProvinceID: 6},
	{ID: 110, Name: "Kabupaten Penukal Abab Lematang Ilir", ProvinceID: 6},
	{ID: 111, Name: "Kota Lubuklinggau", ProvinceID: 6},
	{ID: 112, Name: "Kota Pagar Alam", ProvinceID: 6},
	{ID: 113, Name: "Kota Palembang", ProvinceID: 6},
	{ID: 114, Name: "Kota Prabumulih", ProvinceID: 6},

	// Kota dan kabupaten di Provinsi Bengkulu
	{ID: 115, Name: "Kabupaten Bengkulu Selatan", ProvinceID: 7},
	{ID: 116, Name: "Kabupaten Bengkulu Tengah", ProvinceID: 7},
	{ID: 117, Name: "Kabupaten Bengkulu Utara", ProvinceID: 7},
	{ID: 118, Name: "Kabupaten Kaur", ProvinceID: 7},
	{ID: 119, Name: "Kabupaten Kepahiang", ProvinceID: 7},
	{ID: 120, Name: "Kabupaten Lebong", ProvinceID: 7},
	{ID: 121, Name: "Kabupaten Mukomuko", ProvinceID: 7},
	{ID: 122, Name: "Kabupaten Rejang Lebong", ProvinceID: 7},
	{ID: 123, Name: "Kabupaten Seluma", ProvinceID: 7},
	{ID: 124, Name: "Kota Bengkulu", ProvinceID: 7},

	// Kota dan kabupaten di Provinsi Lampung
	{ID: 125, Name: "Kabupaten Lampung Barat", ProvinceID: 8},
	{ID: 126, Name: "Kabupaten Lampung Selatan", ProvinceID: 8},
	{ID: 127, Name: "Kabupaten Lampung Tengah", ProvinceID: 8},
	{ID: 128, Name: "Kabupaten Lampung Timur", ProvinceID: 8},
	{ID: 129, Name: "Kabupaten Lampung Utara", ProvinceID: 8},
	{ID: 130, Name: "Kabupaten Mesuji", ProvinceID: 8},
	{ID: 131, Name: "Kabupaten Pesawaran", ProvinceID: 8},
	{ID: 132, Name: "Kabupaten Pesisir Barat", ProvinceID: 8},
	{ID: 133, Name: "Kabupaten Pringsewu", ProvinceID: 8},
	{ID: 134, Name: "Kabupaten Tanggamus", ProvinceID: 8},
	{ID: 135, Name: "Kabupaten Tulang Bawang", ProvinceID: 8},
	{ID: 136, Name: "Kabupaten Tulang Bawang Barat", ProvinceID: 8},
	{ID: 137, Name: "Kabupaten Way Kanan", ProvinceID: 8},
	{ID: 138, Name: "Kota Bandar Lampung", ProvinceID: 8},
	{ID: 139, Name: "Kota Metro", ProvinceID: 8},

	// Kota dan kabupaten di Provinsi Kepulauan Bangka Belitung
	{ID: 140, Name: "Kabupaten Bangka", ProvinceID: 9},
	{ID: 141, Name: "Kabupaten Bangka Barat", ProvinceID: 9},
	{ID: 142, Name: "Kabupaten Bangka Selatan", ProvinceID: 9},
	{ID: 143, Name: "Kabupaten Bangka Tengah", ProvinceID: 9},
	{ID: 144, Name: "Kabupaten Belitung", ProvinceID: 9},
	{ID: 145, Name: "Kabupaten Belitung Timur", ProvinceID: 9},
	{ID: 146, Name: "Kota Pangkal Pinang", ProvinceID: 9},

	// Kota dan kabupaten di Provinsi Kepulauan Riau
	{ID: 147, Name: "Kabupaten Bintan", ProvinceID: 10},
	{ID: 148, Name: "Kabupaten Karimun", ProvinceID: 10},
	{ID: 149, Name: "Kabupaten Kepulauan Anambas", ProvinceID: 10},
	{ID: 150, Name: "Kabupaten Lingga", ProvinceID: 10},
	{ID: 151, Name: "Kabupaten Natuna", ProvinceID: 10},
	{ID: 152, Name: "Kota Batam", ProvinceID: 10},
	{ID: 153, Name: "Kota Tanjung Pinang", ProvinceID: 10},

	// Kota dan kabupaten di Provinsi DKI Jakarta
	{ID: 154, Name: "Kabupaten Kepulauan Seribu", ProvinceID: 11},
	{ID: 155, Name: "Kota Jakarta Barat", ProvinceID: 11},
	{ID: 156, Name: "Kota Jakarta Pusat", ProvinceID: 11},
	{ID: 157, Name: "Kota Jakarta Selatan", ProvinceID: 11},
	{ID: 158, Name: "Kota Jakarta Timur", ProvinceID: 11},
	{ID: 159, Name: "Kota Jakarta Utara", ProvinceID: 11},

	// Kota dan kabupaten di Provinsi Jawa Barat

	{ID: 160, Name: "Kabupaten Bandung", ProvinceID: 12},
	{ID: 161, Name: "Kabupaten Bandung Barat", ProvinceID: 12},
	{ID: 162, Name: "Kabupaten Bekasi", ProvinceID: 12},
	{ID: 163, Name: "Kabupaten Bogor", ProvinceID: 12},
	{ID: 164, Name: "Kabupaten Ciamis", ProvinceID: 12},
	{ID: 165, Name: "Kabupaten Cianjur", ProvinceID: 12},
	{ID: 166, Name: "Kabupaten Cirebon", ProvinceID: 12},
	{ID: 167, Name: "Kabupaten Garut", ProvinceID: 12},
	{ID: 168, Name: "Kabupaten Indramayu", ProvinceID: 12},
	{ID: 169, Name: "Kabupaten Karawang", ProvinceID: 12},
	{ID: 170, Name: "Kabupaten Kuningan", ProvinceID: 12},
	{ID: 171, Name: "Kabupaten Majalengka", ProvinceID: 12},
	{ID: 172, Name: "Kabupaten Subang", ProvinceID: 12},
	{ID: 173, Name: "Kabupaten Sukabumi", ProvinceID: 12},
	{ID: 174, Name: "Kabupaten Sumedang", ProvinceID: 12},
	{ID: 175, Name: "Kabupaten Tasikmalaya", ProvinceID: 12},
	{ID: 176, Name: "Kota Bandung", ProvinceID: 12},
	{ID: 177, Name: "Kota Bekasi", ProvinceID: 12},
	{ID: 178, Name: "Kota Bogor", ProvinceID: 12},
	{ID: 179, Name: "Kota Cimahi", ProvinceID: 12},
	{ID: 180, Name: "Kota Cirebon", ProvinceID: 12},
	{ID: 181, Name: "Kota Depok", ProvinceID: 12},
	{ID: 182, Name: "Kota Sukabumi", ProvinceID: 12},
	{ID: 183, Name: "Kota Tasikmalaya", ProvinceID: 12},

	// Kota dan kabupaten di Provinsi Jawa Tengah
	{ID: 184, Name: "Kabupaten Banjarnegara", ProvinceID: 13},
	{ID: 185, Name: "Kabupaten Banyumas", ProvinceID: 13},
	{ID: 186, Name: "Kabupaten Blora", ProvinceID: 13},
	{ID: 187, Name: "Kabupaten Boyolali", ProvinceID: 13},
	{ID: 188, Name: "Kabupaten Brebes", ProvinceID: 13},
	{ID: 189, Name: "Kabupaten Cilacap", ProvinceID: 13},
	{ID: 190, Name: "Kabupaten Demak", ProvinceID: 13},
	{ID: 191, Name: "Kabupaten Grobogan", ProvinceID: 13},
	{ID: 192, Name: "Kabupaten Jepara", ProvinceID: 13},
	{ID: 193, Name: "Kabupaten Karanganyar", ProvinceID: 13},
	{ID: 194, Name: "Kabupaten Kebumen", ProvinceID: 13},
	{ID: 195, Name: "Kabupaten Kendal", ProvinceID: 13},
	{ID: 196, Name: "Kabupaten Klaten", ProvinceID: 13},
	{ID: 197, Name: "Kabupaten Kudus", ProvinceID: 13},
	{ID: 198, Name: "Kabupaten Magelang", ProvinceID: 13},
	{ID: 199, Name: "Kabupaten Pati", ProvinceID: 13},
	{ID: 200, Name: "Kabupaten Pekalongan", ProvinceID: 13},
	{ID: 201, Name: "Kabupaten Pemalang", ProvinceID: 13},
	{ID: 202, Name: "Kabupaten Purworejo", ProvinceID: 13},
	{ID: 203, Name: "Kabupaten Semarang", ProvinceID: 13},
	{ID: 204, Name: "Kabupaten Sragen", ProvinceID: 13},
	{ID: 205, Name: "Kabupaten Sukoharjo", ProvinceID: 13},
	{ID: 206, Name: "Kabupaten Tegal", ProvinceID: 13},
	{ID: 207, Name: "Kota Magelang", ProvinceID: 13},
	{ID: 208, Name: "Kota Pekalongan", ProvinceID: 13},
	{ID: 209, Name: "Kota Salatiga", ProvinceID: 13},
	{ID: 210, Name: "Kota Semarang", ProvinceID: 13},
	{ID: 211, Name: "Kota Surakarta", ProvinceID: 13},
	{ID: 212, Name: "Kota Tegal", ProvinceID: 13},

	// Kota dan kabupaten di Provinsi DI Yogyakarta
	{ID: 213, Name: "Kabupaten Bantul", ProvinceID: 14},
	{ID: 214, Name: "Kabupaten Gunungkidul", ProvinceID: 14},
	{ID: 215, Name: "Kabupaten Kulon Progo", ProvinceID: 14},
	{ID: 216, Name: "Kabupaten Sleman", ProvinceID: 14},
	{ID: 217, Name: "Kota Yogyakarta", ProvinceID: 14},

	// Kota dan kabupaten di Provinsi Jawa Timur
	{ID: 218, Name: "Kabupaten Banyuwangi", ProvinceID: 15},
	{ID: 219, Name: "Kabupaten Blitar", ProvinceID: 15},
	{ID: 220, Name: "Kabupaten Bojonegoro", ProvinceID: 15},
	{ID: 221, Name: "Kabupaten Bondowoso", ProvinceID: 15},
	{ID: 222, Name: "Kabupaten Gresik", ProvinceID: 15},
	{ID: 223, Name: "Kabupaten Jember", ProvinceID: 15},
	{ID: 224, Name: "Kabupaten Jombang", ProvinceID: 15},
	{ID: 225, Name: "Kabupaten Kediri", ProvinceID: 15},
	{ID: 226, Name: "Kabupaten Lamongan", ProvinceID: 15},
	{ID: 227, Name: "Kabupaten Lumajang", ProvinceID: 15},
	{ID: 228, Name: "Kabupaten Madiun", ProvinceID: 15},
	{ID: 229, Name: "Kabupaten Magetan", ProvinceID: 15},
	{ID: 230, Name: "Kabupaten Malang", ProvinceID: 15},
	{ID: 231, Name: "Kabupaten Mojokerto", ProvinceID: 15},
	{ID: 232, Name: "Kabupaten Nganjuk", ProvinceID: 15},
	{ID: 233, Name: "Kabupaten Ngawi", ProvinceID: 15},
	{ID: 234, Name: "Kabupaten Pacitan", ProvinceID: 15},
	{ID: 235, Name: "Kabupaten Pamekasan", ProvinceID: 15},
	{ID: 236, Name: "Kabupaten Pasuruan", ProvinceID: 15},
	{ID: 237, Name: "Kabupaten Ponorogo", ProvinceID: 15},
	{ID: 238, Name: "Kabupaten Probolinggo", ProvinceID: 15},
	{ID: 239, Name: "Kabupaten Sampang", ProvinceID: 15},
	{ID: 240, Name: "Kabupaten Sidoarjo", ProvinceID: 15},
	{ID: 241, Name: "Kabupaten Situbondo", ProvinceID: 15},
	{ID: 242, Name: "Kabupaten Sumenep", ProvinceID: 15},
	{ID: 243, Name: "Kabupaten Trenggalek", ProvinceID: 15},
	{ID: 244, Name: "Kabupaten Tulungagung", ProvinceID: 15},
	{ID: 245, Name: "Kota Batu", ProvinceID: 15},
	{ID: 246, Name: "Kota Blitar", ProvinceID: 15},
	{ID: 247, Name: "Kota Kediri", ProvinceID: 15},
	{ID: 248, Name: "Kota Madiun", ProvinceID: 15},
	{ID: 249, Name: "Kota Malang", ProvinceID: 15},
	{ID: 250, Name: "Kota Mojokerto", ProvinceID: 15},
	{ID: 251, Name: "Kota Pasuruan", ProvinceID: 15},
	{ID: 252, Name: "Kota Probolinggo", ProvinceID: 15},
	{ID: 253, Name: "Kota Surabaya", ProvinceID: 15},

	// Kota dan kabupaten di Provinsi Banten
	{ID: 254, Name: "Kabupaten Banten", ProvinceID: 16},
	{ID: 255, Name: "Kabupaten Lebak", ProvinceID: 16},
	{ID: 256, Name: "Kabupaten Pandeglang", ProvinceID: 16},
	{ID: 257, Name: "Kabupaten Serang", ProvinceID: 16},
	{ID: 258, Name: "Kota Cilegon", ProvinceID: 16},
	{ID: 259, Name: "Kota Serang", ProvinceID: 16},
	{ID: 260, Name: "Kota Tangerang", ProvinceID: 16},
	{ID: 261, Name: "Kota Tangerang Selatan", ProvinceID: 16},

	// Kota dan kabupaten di Provinsi Bali
	{ID: 262, Name: "Kabupaten Badung", ProvinceID: 17},
	{ID: 263, Name: "Kabupaten Bangli", ProvinceID: 17},
	{ID: 264, Name: "Kabupaten Buleleng", ProvinceID: 17},
	{ID: 265, Name: "Kabupaten Gianyar", ProvinceID: 17},
	{ID: 266, Name: "Kabupaten Jembrana", ProvinceID: 17},
	{ID: 267, Name: "Kabupaten Karangasem", ProvinceID: 17},
	{ID: 268, Name: "Kabupaten Klungkung", ProvinceID: 17},
	{ID: 269, Name: "Kota Denpasar", ProvinceID: 17},

	// Kota dan kabupaten di Provinsi Nusa Tenggara Barat
	{ID: 270, Name: "Kabupaten Bima", ProvinceID: 18},
	{ID: 271, Name: "Kabupaten Dompu", ProvinceID: 18},
	{ID: 272, Name: "Kabupaten Lombok Barat", ProvinceID: 18},
	{ID: 273, Name: "Kabupaten Lombok Tengah", ProvinceID: 18},
	{ID: 274, Name: "Kabupaten Lombok Timur", ProvinceID: 18},
	{ID: 275, Name: "Kabupaten Sumbawa", ProvinceID: 18},
	{ID: 276, Name: "Kabupaten Sumbawa Barat", ProvinceID: 18},
	{ID: 277, Name: "Kota Mataram", ProvinceID: 18},
	{ID: 278, Name: "Kota Bima", ProvinceID: 18},

	// Kota dan kabupaten di Provinsi Nusa Tenggara Timur
	{ID: 279, Name: "Kabupaten Alor", ProvinceID: 19},
	{ID: 280, Name: "Kabupaten Belu", ProvinceID: 19},
	{ID: 281, Name: "Kabupaten Ende", ProvinceID: 19},
	{ID: 282, Name: "Kabupaten Flores Timur", ProvinceID: 19},
	{ID: 283, Name: "Kabupaten Lembata", ProvinceID: 19},
	{ID: 284, Name: "Kabupaten Manggarai", ProvinceID: 19},
	{ID: 285, Name: "Kabupaten Manggarai Barat", ProvinceID: 19},
	{ID: 286, Name: "Kabupaten Manggarai Timur", ProvinceID: 19},
	{ID: 287, Name: "Kabupaten Nagekeo", ProvinceID: 19},
	{ID: 288, Name: "Kabupaten Ngada", ProvinceID: 19},
	{ID: 289, Name: "Kabupaten Rote Ndao", ProvinceID: 19},
	{ID: 290, Name: "Kabupaten Sabu Raijua", ProvinceID: 19},
	{ID: 291, Name: "Kabupaten Sikka", ProvinceID: 19},
	{ID: 292, Name: "Kabupaten Sumba Barat", ProvinceID: 19},
	{ID: 293, Name: "Kabupaten Sumba Barat Daya", ProvinceID: 19},
	{ID: 294, Name: "Kabupaten Sumba Timur", ProvinceID: 19},
	{ID: 295, Name: "Kabupaten Timor Tengah Selatan", ProvinceID: 19},
	{ID: 296, Name: "Kabupaten Timor Tengah Utara", ProvinceID: 19},
	{ID: 297, Name: "Kota Kupang", ProvinceID: 19},

	// Kota dan kabupaten di Provinsi Kalimantan Barat
	{ID: 298, Name: "Kabupaten Bengkayang", ProvinceID: 20},
	{ID: 299, Name: "Kabupaten Kapuas Hulu", ProvinceID: 20},
	{ID: 300, Name: "Kabupaten Kayong Utara", ProvinceID: 20},
	{ID: 301, Name: "Kabupaten Ketapang", ProvinceID: 20},
	{ID: 302, Name: "Kabupaten Kubu Raya", ProvinceID: 20},
	{ID: 303, Name: "Kabupaten Landak", ProvinceID: 20},
	{ID: 304, Name: "Kabupaten Melawi", ProvinceID: 20},
	{ID: 305, Name: "Kabupaten Sambas", ProvinceID: 20},
	{ID: 306, Name: "Kabupaten Sanggau", ProvinceID: 20},
	{ID: 307, Name: "Kabupaten Sekadau", ProvinceID: 20},
	{ID: 308, Name: "Kabupaten Sintang", ProvinceID: 20},
	{ID: 309, Name: "Kota Pontianak", ProvinceID: 20},
	{ID: 310, Name: "Kota Singkawang", ProvinceID: 20},

	// Kota dan kabupaten di Provinsi Kalimantan Tengah
	{ID: 311, Name: "Kabupaten Barito Selatan", ProvinceID: 21},
	{ID: 312, Name: "Kabupaten Barito Timur", ProvinceID: 21},
	{ID: 313, Name: "Kabupaten Barito Utara", ProvinceID: 21},
	{ID: 314, Name: "Kabupaten Gunung Mas", ProvinceID: 21},
	{ID: 315, Name: "Kabupaten Kapuas", ProvinceID: 21},
	{ID: 316, Name: "Kabupaten Katingan", ProvinceID: 21},
	{ID: 317, Name: "Kabupaten Kotawaringin Barat", ProvinceID: 21},
	{ID: 318, Name: "Kabupaten Kotawaringin Timur", ProvinceID: 21},
	{ID: 319, Name: "Kabupaten Lamandau", ProvinceID: 21},
	{ID: 320, Name: "Kabupaten Murung Raya", ProvinceID: 21},
	{ID: 321, Name: "Kabupaten Pulang Pisau", ProvinceID: 21},
	{ID: 322, Name: "Kabupaten Sukamara", ProvinceID: 21},
	{ID: 323, Name: "Kabupaten Seruyan", ProvinceID: 21},
	{ID: 324, Name: "Kota Palangka Raya", ProvinceID: 21},

	// Kota dan kabupaten di Provinsi Kalimantan Selatan
	{ID: 325, Name: "Kabupaten Balangan", ProvinceID: 22},
	{ID: 326, Name: "Kabupaten Banjar", ProvinceID: 22},
	{ID: 327, Name: "Kabupaten Barito Kuala", ProvinceID: 22},
	{ID: 328, Name: "Kabupaten Hulu Sungai Selatan", ProvinceID: 22},
	{ID: 329, Name: "Kabupaten Hulu Sungai Tengah", ProvinceID: 22},
	{ID: 330, Name: "Kabupaten Hulu Sungai Utara", ProvinceID: 22},
	{ID: 331, Name: "Kabupaten Kotabaru", ProvinceID: 22},
	{ID: 332, Name: "Kabupaten Tanah Bumbu", ProvinceID: 22},
	{ID: 333, Name: "Kabupaten Tanah Laut", ProvinceID: 22},
	{ID: 334, Name: "Kabupaten Tabalong", ProvinceID: 22},
	{ID: 335, Name: "Kabupaten Tapin", ProvinceID: 22},
	{ID: 336, Name: "Kota Banjarbaru", ProvinceID: 22},
	{ID: 337, Name: "Kota Banjarmasin", ProvinceID: 22},

	// Kota dan kabupaten di Provinsi Kalimantan Timur
	{ID: 338, Name: "Kabupaten Berau", ProvinceID: 23},
	{ID: 339, Name: "Kabupaten Kutai Barat", ProvinceID: 23},
	{ID: 340, Name: "Kabupaten Kutai Kartanegara", ProvinceID: 23},
	{ID: 341, Name: "Kabupaten Kutai Timur", ProvinceID: 23},
	{ID: 342, Name: "Kabupaten Mahakam Ulu", ProvinceID: 23},
	{ID: 343, Name: "Kabupaten Paser", ProvinceID: 23},
	{ID: 344, Name: "Kabupaten Penajam Paser Utara", ProvinceID: 23},
	{ID: 345, Name: "Kota Balikpapan", ProvinceID: 23},
	{ID: 346, Name: "Kota Bontang", ProvinceID: 23},
	{ID: 347, Name: "Kota Samarinda", ProvinceID: 23},

	// Kota dan kabupaten di Provinsi Kalimantan Utara
	{ID: 348, Name: "Kabupaten Bulungan", ProvinceID: 24},
	{ID: 349, Name: "Kabupaten Malinau", ProvinceID: 24},
	{ID: 350, Name: "Kabupaten Nunukan", ProvinceID: 24},
	{ID: 351, Name: "Kabupaten Tana Tidung", ProvinceID: 24},
	{ID: 352, Name: "Kota Tarakan", ProvinceID: 24},

	// Kota dan kabupaten di Provinsi Sulawesi Utara
	{ID: 353, Name: "Kabupaten Bolaang Mongondow", ProvinceID: 25},
	{ID: 354, Name: "Kabupaten Bolaang Mongondow Selatan", ProvinceID: 25},
	{ID: 355, Name: "Kabupaten Bolaang Mongondow Timur", ProvinceID: 25},
	{ID: 356, Name: "Kabupaten Bolaang Mongondow Utara", ProvinceID: 25},
	{ID: 357, Name: "Kabupaten Minahasa", ProvinceID: 25},
	{ID: 358, Name: "Kabupaten Minahasa Selatan", ProvinceID: 25},
	{ID: 359, Name: "Kabupaten Minahasa Tenggara", ProvinceID: 25},
	{ID: 360, Name: "Kabupaten Minahasa Utara", ProvinceID: 25},
	{ID: 361, Name: "Kabupaten Siau Tagulandang Biaro", ProvinceID: 25},
	{ID: 362, Name: "Kabupaten Kepulauan Sangihe", ProvinceID: 25},
	{ID: 363, Name: "Kabupaten Kepulauan Talaud", ProvinceID: 25},
	{ID: 364, Name: "Kota Bitung", ProvinceID: 25},
	{ID: 365, Name: "Kota Manado", ProvinceID: 25},
	{ID: 366, Name: "Kota Tomohon", ProvinceID: 25},

	// Kota dan kabupaten di Provinsi Sulawesi Tengah
	{ID: 367, Name: "Kabupaten Banggai", ProvinceID: 26},
	{ID: 368, Name: "Kabupaten Banggai Kepulauan", ProvinceID: 26},
	{ID: 369, Name: "Kabupaten Buol", ProvinceID: 26},
	{ID: 370, Name: "Kabupaten Donggala", ProvinceID: 26},
	{ID: 371, Name: "Kabupaten Morowali", ProvinceID: 26},
	{ID: 372, Name: "Kabupaten Morowali Utara", ProvinceID: 26},
	{ID: 373, Name: "Kabupaten Poso", ProvinceID: 26},
	{ID: 374, Name: "Kabupaten Sigi", ProvinceID: 26},
	{ID: 375, Name: "Kabupaten Tojo Una-Una", ProvinceID: 26},
	{ID: 376, Name: "Kota Palu", ProvinceID: 26},

	// Kota dan kabupaten di Provinsi Sulawesi Selatan
	{ID: 377, Name: "Kabupaten Bantaeng", ProvinceID: 27},
	{ID: 378, Name: "Kabupaten Barru", ProvinceID: 27},
	{ID: 379, Name: "Kabupaten Bone", ProvinceID: 27},
	{ID: 380, Name: "Kabupaten Bulukumba", ProvinceID: 27},
	{ID: 381, Name: "Kabupaten Enrekang", ProvinceID: 27},
	{ID: 382, Name: "Kabupaten Gowa", ProvinceID: 27},
	{ID: 383, Name: "Kabupaten Jeneponto", ProvinceID: 27},
	{ID: 384, Name: "Kabupaten Luwu", ProvinceID: 27},
	{ID: 385, Name: "Kabupaten Luwu Timur", ProvinceID: 27},
	{ID: 386, Name: "Kabupaten Luwu Utara", ProvinceID: 27},
	{ID: 387, Name: "Kabupaten Maros", ProvinceID: 27},
	{ID: 388, Name: "Kabupaten Pangkajene Kepulauan", ProvinceID: 27},
	{ID: 389, Name: "Kabupaten Pinrang", ProvinceID: 27},
	{ID: 390, Name: "Kabupaten Sidenreng Rappang", ProvinceID: 27},
	{ID: 391, Name: "Kabupaten Sinjai", ProvinceID: 27},
	{ID: 392, Name: "Kabupaten Soppeng", ProvinceID: 27},
	{ID: 393, Name: "Kabupaten Takalar", ProvinceID: 27},
	{ID: 394, Name: "Kabupaten Tana Toraja", ProvinceID: 27},
	{ID: 395, Name: "Kabupaten Toraja Utara", ProvinceID: 27},
	{ID: 396, Name: "Kota Makassar", ProvinceID: 27},
	{ID: 397, Name: "Kota Palopo", ProvinceID: 27},
	{ID: 398, Name: "Kota Parepare", ProvinceID: 27},

	// Kota dan kabupaten di Provinsi Sulawesi Tenggara
	{ID: 399, Name: "Kabupaten Buton", ProvinceID: 28},
	{ID: 400, Name: "Kabupaten Buton Utara", ProvinceID: 28},
	{ID: 401, Name: "Kabupaten Kolaka", ProvinceID: 28},
	{ID: 402, Name: "Kabupaten Kolaka Utara", ProvinceID: 28},
	{ID: 403, Name: "Kabupaten Konawe", ProvinceID: 28},
	{ID: 404, Name: "Kabupaten Konawe Kepulauan", ProvinceID: 28},
	{ID: 405, Name: "Kabupaten Konawe Utara", ProvinceID: 28},
	{ID: 406, Name: "Kabupaten Muna", ProvinceID: 28},
	{ID: 407, Name: "Kabupaten Muna Barat", ProvinceID: 28},
	{ID: 408, Name: "Kabupaten Wakatobi", ProvinceID: 28},
	{ID: 409, Name: "Kota Baubau", ProvinceID: 28},
	{ID: 410, Name: "Kota Kendari", ProvinceID: 28},

	// Kota dan kabupaten di Provinsi Gorontalo
	{ID: 411, Name: "Kabupaten Boalemo", ProvinceID: 29},
	{ID: 412, Name: "Kabupaten Bone Bolango", ProvinceID: 29},
	{ID: 413, Name: "Kabupaten Gorontalo", ProvinceID: 29},
	{ID: 414, Name: "Kabupaten Gorontalo Utara", ProvinceID: 29},
	{ID: 415, Name: "Kabupaten Pohuwato", ProvinceID: 29},
	{ID: 416, Name: "Kota Gorontalo", ProvinceID: 29},

	// Kota dan kabupaten di Provinsi Sulawesi Barat
	{ID: 417, Name: "Kabupaten Majene", ProvinceID: 30},
	{ID: 418, Name: "Kabupaten Mamuju", ProvinceID: 30},
	{ID: 419, Name: "Kabupaten Mamuju Tengah", ProvinceID: 30},
	{ID: 420, Name: "Kabupaten Polewali Mandar", ProvinceID: 30},
	{ID: 421, Name: "Kota Mamuju", ProvinceID: 30},

	// Kota dan kabupaten di Provinsi Maluku
	{ID: 422, Name: "Kabupaten Buru", ProvinceID: 31},
	{ID: 423, Name: "Kabupaten Buru Selatan", ProvinceID: 31},
	{ID: 424, Name: "Kabupaten Kepulauan Aru", ProvinceID: 31},
	{ID: 425, Name: "Kabupaten Maluku Barat Daya", ProvinceID: 31},
	{ID: 426, Name: "Kabupaten Maluku Tengah", ProvinceID: 31},
	{ID: 427, Name: "Kabupaten Maluku Tenggara", ProvinceID: 31},
	{ID: 428, Name: "Kabupaten Seram Bagian Barat", ProvinceID: 31},
	{ID: 429, Name: "Kabupaten Seram Bagian Timur", ProvinceID: 31},
	{ID: 430, Name: "Kota Ambon", ProvinceID: 31},
	{ID: 431, Name: "Kota Tual", ProvinceID: 31},

	// Kota dan kabupaten di Provinsi Maluku Utara
	{ID: 432, Name: "Kabupaten Halmahera Barat", ProvinceID: 32},
	{ID: 433, Name: "Kabupaten Halmahera Selatan", ProvinceID: 32},
	{ID: 434, Name: "Kabupaten Halmahera Tengah", ProvinceID: 32},
	{ID: 435, Name: "Kabupaten Halmahera Timur", ProvinceID: 32},
	{ID: 436, Name: "Kabupaten Kepulauan Sula", ProvinceID: 32},
	{ID: 437, Name: "Kabupaten Pulau Morotai", ProvinceID: 32},
	{ID: 438, Name: "Kota Ternate", ProvinceID: 32},
	{ID: 439, Name: "Kota Tidore Kepulauan", ProvinceID: 32},

	// Kota dan kabupaten di Provinsi Papua
	{ID: 440, Name: "Kabupaten Asmat", ProvinceID: 33},
	{ID: 441, Name: "Kabupaten Biak Numfor", ProvinceID: 33},
	{ID: 442, Name: "Kabupaten Deiyai", ProvinceID: 33},
	{ID: 443, Name: "Kabupaten Dogiyai", ProvinceID: 33},
	{ID: 444, Name: "Kabupaten Intan Jaya", ProvinceID: 33},
	{ID: 445, Name: "Kabupaten Jayapura", ProvinceID: 33},
	{ID: 446, Name: "Kabupaten Jayawijaya", ProvinceID: 33},
	{ID: 447, Name: "Kabupaten Keerom", ProvinceID: 33},
	{ID: 448, Name: "Kabupaten Mamberamo Raya", ProvinceID: 33},
	{ID: 449, Name: "Kabupaten Mappi", ProvinceID: 33},
	{ID: 450, Name: "Kabupaten Merauke", ProvinceID: 33},
	{ID: 451, Name: "Kabupaten Mimika", ProvinceID: 33},
	{ID: 452, Name: "Kabupaten Nduga", ProvinceID: 33},
	{ID: 453, Name: "Kabupaten Paniai", ProvinceID: 33},
	{ID: 454, Name: "Kabupaten Puncak", ProvinceID: 33},
	{ID: 455, Name: "Kabupaten Puncak Jaya", ProvinceID: 33},
	{ID: 456, Name: "Kabupaten Sarmi", ProvinceID: 33},
	{ID: 457, Name: "Kabupaten Supiori", ProvinceID: 33},
	{ID: 458, Name: "Kabupaten Waropen", ProvinceID: 33},
	{ID: 459, Name: "Kota Jayapura", ProvinceID: 33},

	// Kota dan kabupaten di Provinsi Papua Barat
	{ID: 460, Name: "Kabupaten Fakfak", ProvinceID: 34},
	{ID: 461, Name: "Kabupaten Kaimana", ProvinceID: 34},
	{ID: 462, Name: "Kabupaten Manokwari", ProvinceID: 34},
	{ID: 463, Name: "Kabupaten Maybrat", ProvinceID: 34},
	{ID: 464, Name: "Kabupaten Raja Ampat", ProvinceID: 34},
	{ID: 465, Name: "Kabupaten Sorong", ProvinceID: 34},
	{ID: 466, Name: "Kabupaten Sorong Selatan", ProvinceID: 34},
	{ID: 467, Name: "Kota Sorong", ProvinceID: 34},

	// Kota dan kabupaten di Provinsi Papua Selatan
	{ID: 468, Name: "Kabupaten Boven Digoel", ProvinceID: 35},
	{ID: 469, Name: "Kabupaten Mappi", ProvinceID: 35},
	{ID: 470, Name: "Kabupaten Merauke", ProvinceID: 35},
	{ID: 471, Name: "Kota Merauke", ProvinceID: 35},

	// Kota dan kabupaten di Provinsi Papua Tengah
	{ID: 472, Name: "Kabupaten Jayawijaya", ProvinceID: 36},
	{ID: 473, Name: "Kabupaten Mamberamo Tengah", ProvinceID: 36},
	{ID: 474, Name: "Kabupaten Puncak Jaya", ProvinceID: 36},
	{ID: 475, Name: "Kota Wamena", ProvinceID: 36},

	// Kota dan kabupaten di Provinsi Papua Pegunungan
	{ID: 476, Name: "Kabupaten Jayapura", ProvinceID: 37},
	{ID: 477, Name: "Kabupaten Lanny Jaya", ProvinceID: 37},
	{ID: 478, Name: "Kabupaten Nduga", ProvinceID: 37},
	{ID: 479, Name: "Kota Papua Pegunungan", ProvinceID: 37},

	// Kota dan kabupaten di Provinsi Papua Barat Daya
	{ID: 480, Name: "Kabupaten Raja Ampat", ProvinceID: 38},
	{ID: 481, Name: "Kabupaten Sorong Selatan", ProvinceID: 38},
	{ID: 482, Name: "Kota Sorong", ProvinceID: 38},
}

var provinces = []*domain.Province{
	{ID: 1, Name: "Nanggroe Aceh Darussalam"},
	{ID: 2, Name: "Sumatera Utara"},
	{ID: 3, Name: "Sumatera Barat"},
	{ID: 4, Name: "Riau"},
	{ID: 5, Name: "Jambi"},
	{ID: 6, Name: "Sumatera Selatan"},
	{ID: 7, Name: "Bengkulu"},
	{ID: 8, Name: "Lampung"},
	{ID: 9, Name: "Kepulauan Bangka Belitung"},
	{ID: 10, Name: "Kepulauan Riau"},
	{ID: 11, Name: "DKI Jakarta"},
	{ID: 12, Name: "Jawa Barat"},
	{ID: 13, Name: "Jawa Tengah"},
	{ID: 14, Name: "DI Yogyakarta"},
	{ID: 15, Name: "Jawa Timur"},
	{ID: 16, Name: "Banten"},
	{ID: 17, Name: "Bali"},
	{ID: 18, Name: "Nusa Tenggara Barat"},
	{ID: 19, Name: "Nusa Tenggara Timur"},
	{ID: 20, Name: "Kalimantan Barat"},
	{ID: 21, Name: "Kalimantan Tengah"},
	{ID: 22, Name: "Kalimantan Selatan"},
	{ID: 23, Name: "Kalimantan Timur"},
	{ID: 24, Name: "Kalimantan Utara"},
	{ID: 25, Name: "Sulawesi Utara"},
	{ID: 26, Name: "Sulawesi Tengah"},
	{ID: 27, Name: "Sulawesi Selatan"},
	{ID: 28, Name: "Sulawesi Tenggara"},
	{ID: 29, Name: "Gorontalo"},
	{ID: 30, Name: "Sulawesi Barat"},
	{ID: 31, Name: "Maluku"},
	{ID: 32, Name: "Maluku Utara"},
	{ID: 33, Name: "Papua"},
	{ID: 34, Name: "Papua Barat"},
	{ID: 35, Name: "Papua Selatan"},
	{ID: 36, Name: "Papua Tengah"},
	{ID: 37, Name: "Papua Pegunungan"},
	{ID: 38, Name: "Papua Barat Daya"},
}

var commodities = []*domain.Commodity{
	{
		ID:          uuid.New(),
		Name:        "Rice",
		Description: "Rice is a staple food crop in many parts of the world. It is a cereal grain that is the seed of the rice plant. It is a cereal grain that is the seed of the rice plant.",
		Code:        "RICE",
		Duration:    "90 days",
	},
	{
		ID:          uuid.New(),
		Name:        "Corn",
		Description: "Corn is a staple food crop in many parts of the world. It is a cereal grain that is the seed of the corn plant. It is a cereal grain that is the seed of the corn plant.",
		Code:        "CORN",
		Duration:    "90 days",
	},
	{
		ID:          uuid.New(),
		Name:        "Soybean",
		Description: "Soybean is a staple food crop in many parts of the world. It is a cereal grain that is the seed of the soybean plant. It is a cereal grain that is the seed of the soybean plant.",
		Code:        "SOYBEAN",
		Duration:    "70 days",
	},
	{
		ID:          uuid.New(),
		Name:        "Wheat",
		Description: "Wheat is a staple food crop in many parts of the world. It is a cereal grain that is the seed of the wheat plant. It is a cereal grain that is the seed of the wheat plant.",
		Code:        "WHEAT",
		Duration:    "120 days",
	},
}

func password() string {
	password, err := utils.NewHasher().HashPassword("password")
	if err != nil {
		log.Fatalf("Error seeding users: %v", err)
		return ""
	}
	return password
}

var phone = "08123456789"
var users = []*domain.User{
	{
		ID:       uuid.New(),
		RoleID:   1,
		Name:     "Admin",
		Email:    "admin@example.com",
		Password: password(),
		Phone:    &phone,
	},
	{
		ID:       uuid.New(),
		RoleID:   1,
		Name:     "Farmer",
		Email:    "farmer@example.com",
		Password: password(),
		Phone:    &phone,
	},
}

var roles = []*domain.Role{
	{ID: 1, Name: "Admin"},
	{ID: 2, Name: "Farmer"},
}

var lands = []*domain.Land{
	{
		ID:          uuid.New(),
		UserID:      users[0].ID,
		LandArea:    1000,
		Unit:        "ha",
		Certificate: gofakeit.Word() + "-" + gofakeit.LetterN(4),
		CityID:      164,
	},
	{
		ID:          uuid.New(),
		UserID:      users[1].ID,
		LandArea:    1500,
		Unit:        "ha",
		Certificate: gofakeit.Word() + "-" + gofakeit.LetterN(4),
		CityID:      165,
	},
	{
		ID:          uuid.New(),
		UserID:      users[0].ID,
		LandArea:    2000,
		Unit:        "ha",
		Certificate: gofakeit.Word() + "-" + gofakeit.LetterN(4),
		CityID:      165,
	},
	{
		ID:          uuid.New(),
		UserID:      users[1].ID,
		LandArea:    2500,
		Unit:        "ha",
		Certificate: gofakeit.Word() + "-" + gofakeit.LetterN(4),
		CityID:      175,
	},
	{
		ID:          uuid.New(),
		UserID:      users[0].ID,
		LandArea:    3000,
		Unit:        "ha",
		Certificate: gofakeit.Word() + "-" + gofakeit.LetterN(4),
		CityID:      176,
	},
}
